### PR TITLE
This is not a draft anymore

### PR DESCRIPTION
**Pull request by ghost**
Your Pull Request will be updated when you merge this.

### CODE REVIEW

**Comment by ThisTestUser** [comment]
I just wanted to know, but what modern anti-cheats does killaura bypass?

**Comment by Encryptonite** [comment]
It know for sure that it bypasses NoCheat+ and MineplexAntiCheat. Any others I cannot personally verify.

**Comment by ThisTestUser** [comment]
But what do you mean by the most modern ones?

**Comment by Encryptonite** [comment]
The latest versions of the most popular anticheat plugins. As of now, NoCheat+ is the most effective and most popular.

**Comment by ThisTestUser** [comment]
What about AAC?

**Comment by Encryptonite** [comment]
It can detect it. I neglected to consider paid plugins in my research. I joined their test server and experimented with it.

**Comment by ghost** [comment]
@ThisTestUser It bypasses Paramount too.

**Comment by ThisTestUser** [comment]
@mcccs Didn't SirJava post a video saying that Wurst is blocked?

**Comment by ghost** [comment]
It was uploaded before the "Invisible Players" feature in Target menu.

Proof: https://youtu.be/r_IAxkQi_Z4?t=13s

**Comment by ThisTestUser** [comment]
Paramount does not only use NPCS! Even if you do not hit any fake players, you will still be detected. 
(If I remember correctly, Paramount has 2 other methods to detect it besides spawning fake players)

**Comment by ghost** [comment]
Found something more scary. It has **6 other ways** to detect!
https://www.spigotmc.org/threads/wip-paramount-most-powerful-anticheat-system-ever-made.85100/#post-935313

It would be easy to bypass if he uploads it onto the internet.

https://www.spigotmc.org/threads/wip-paramount-most-powerful-anticheat-system-ever-made.85100/#post-935399

Method 2 looks like, it is triggered when Yaw & Pitch are changing suddenly and targeting the target's yaw & pitch exactly.

https://youtu.be/mHVhGOzY0u4

> SilentAim just sends the Server "wrong" (values aimed to the target entity relative to the player's location) yaw/pitch values.
> But there are some alternate ways to get the players correct yaw/pitch values.
> If these compare to the yaw/pitch values the client send before, he uses a silentaim.

https://www.spigotmc.org/threads/wip-paramount-most-powerful-anticheat-system-ever-made.85100/page-2#post-936085

Wurst needs that feature ^

https://www.spigotmc.org/threads/wip-paramount-most-powerful-anticheat-system-ever-made.85100/page-2#post-936567

Wurst should steal Nodus for 1.10 too.

> > The real issue here is that the word 'Paramount' is trademarked.
> 
> THIS is my smallest problem.

Let's tell Viacom! Then Paramount will be dead! Muhaha!

Also Nodus' GUI is much better than Wurst's
https://youtu.be/CG5O8PQ3m9Q
.

**Comment by ThisTestUser** [comment]
https://github.com/ThisTestUser/Docs/blob/master/AntiCheats.md
Paramount is not public.
Also, most clients will not attempt to bypass it, because all their killauras are all the same.
And someone has already done it: https://www.youtube.com/watch?v=5wC0jgleJ2I

**Comment by ghost** [comment]
👍 Nice guide.
Please show alexander that document.

**Pull request merged**
